import React, { useEffect, useRef, useState } from 'react';
import { Compass } from 'lucide-react';
import { cn } from '@/lib/utils';

// "Compass" is this platform's named AI layer — the thing behind Ask, Briefs,
// and score explanations. Naming it turns several separate AI-ish features
// into one recognizable product-within-the-product instead of generic
// "AI-powered" copy repeated in five places.
export const AI_NAME = 'Compass';

export function AiBadge({ className, label }: { className?: string; label?: string }) {
  return (
    <span className={cn("inline-flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-widest text-primary/80 bg-primary/5 border border-primary/10 px-2.5 py-1 rounded-full", className)}>
      <Compass className="w-3 h-3" />
      {label || `Generated by ${AI_NAME}`}
    </span>
  );
}

export function AiThinking({ label = `${AI_NAME} is thinking` }: { label?: string }) {
  return (
    <span className="inline-flex items-center gap-2 text-xs font-bold text-primary/70 uppercase tracking-widest">
      <Compass className="w-3.5 h-3.5 animate-pulse" />
      {label}
      <span className="inline-flex gap-0.5">
        <span className="w-1 h-1 rounded-full bg-primary/60 animate-bounce" style={{ animationDelay: '0ms' }} />
        <span className="w-1 h-1 rounded-full bg-primary/60 animate-bounce" style={{ animationDelay: '150ms' }} />
        <span className="w-1 h-1 rounded-full bg-primary/60 animate-bounce" style={{ animationDelay: '300ms' }} />
      </span>
    </span>
  );
}

// Reveals `text` character-by-character to simulate live generation. Re-runs
// whenever `text` (or `runKey`) changes, so re-opening a brief or re-running
// a query "regenerates" the copy instead of only playing once ever.
export function useTypewriter(text: string, runKey?: string | number, speedMs = 12) {
  const [shown, setShown] = useState('');
  const [done, setDone] = useState(false);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (timerRef.current) clearInterval(timerRef.current);
    if (!text) { setShown(''); setDone(true); return; }
    setShown('');
    setDone(false);
    let i = 0;
    timerRef.current = setInterval(() => {
      i += Math.max(1, Math.round(text.length / 120));
      if (i >= text.length) {
        setShown(text);
        setDone(true);
        if (timerRef.current) clearInterval(timerRef.current);
      } else {
        setShown(text.slice(0, i));
      }
    }, speedMs);
    return () => { if (timerRef.current) clearInterval(timerRef.current); };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [text, runKey]);

  return { shown, done };
}

export function TypewriterText({ text, runKey, className, speedMs, showCursor = true }: { text: string; runKey?: string | number; className?: string; speedMs?: number; showCursor?: boolean }) {
  const { shown, done } = useTypewriter(text, runKey, speedMs);
  return (
    <span className={className}>
      {shown}
      {showCursor && !done && <span className="inline-block w-[2px] h-[1em] bg-current align-middle ml-0.5 animate-pulse" />}
    </span>
  );
}
